python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.1 --error_cols Education --pattern_cols Education EverBenched ExperienceInCurrentDomain Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.2 --error_cols Gender --pattern_cols Gender City_New_Delhi Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.3 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.4 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender Age Education Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.1 --error_cols JoiningYear --pattern_cols JoiningYear PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.2 --error_cols PaymentTier --pattern_cols PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.3 --error_cols Age --pattern_cols Age Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.4 --error_cols JoiningYear --pattern_cols JoiningYear PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender Education Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.1 --error_cols JoiningYear --pattern_cols JoiningYear Gender PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.2 --error_cols JoiningYear --pattern_cols JoiningYear Age City_Pune Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.3 --error_cols JoiningYear --pattern_cols JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.4 --error_cols JoiningYear --pattern_cols JoiningYear Age ExperienceInCurrentDomain Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender Age Education Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.1 --error_cols Education --pattern_cols Education EverBenched Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.2 --error_cols Education --pattern_cols Education ExperienceInCurrentDomain JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.3 --error_cols Age --pattern_cols Age City_Bangalore ExperienceInCurrentDomain Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.4 --error_cols Age --pattern_cols Age City_Pune Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender ExperienceInCurrentDomain JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5