# python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0 --error_cols workclass --pattern_cols workclass Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
# python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.1 --error_cols workclass --pattern_cols workclass Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
# python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.2 --error_cols race --pattern_cols race Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
# python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.3 --error_cols gender --pattern_cols gender Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
# python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.4 --error_cols gender --pattern_cols gender Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
# python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model LR --error_type MNAR --error_pcts 0.5 --error_cols marital --pattern_cols marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0 --error_cols gender --pattern_cols Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.1 --error_cols education --pattern_cols education race marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.2 --error_cols education --pattern_cols education race relationship Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.3 --error_cols education --pattern_cols education gender marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.4 --error_cols education --pattern_cols education gender marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model DT --error_type MNAR --error_pcts 0.5 --error_cols education --pattern_cols education gender marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0 --error_cols gender --pattern_cols Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.1 --error_cols education --pattern_cols education marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.2 --error_cols education --pattern_cols education race relationship Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.3 --error_cols education --pattern_cols education age relationship Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.4 --error_cols education --pattern_cols education gender marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model RF --error_type MNAR --error_pcts 0.5 --error_cols education --pattern_cols education gender marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0 --error_cols gender --pattern_cols Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.1 --error_cols age --pattern_cols age gender marital Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.2 --error_cols hours --pattern_cols hours age Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.3 --error_cols age --pattern_cols age relationship Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.4 --error_cols hours --pattern_cols hours race relationship Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset adult --cleaning KNNImputer --model NN --error_type MNAR --error_pcts 0.5 --error_cols marital --pattern_cols marital age Y --sens_attr gender --objective AUC --n_trials 100 --n_processes 5
