python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model LR --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model LR --error_type MNAR --error_pcts 0.1 --error_cols Education --pattern_cols Education Age City_Pune Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model LR --error_type MNAR --error_pcts 0.2 --error_cols PaymentTier --pattern_cols PaymentTier Age Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model LR --error_type MNAR --error_pcts 0.3 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model LR --error_type MNAR --error_pcts 0.4 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model LR --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model DT --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model DT --error_type MNAR --error_pcts 0.1 --error_cols JoiningYear --pattern_cols JoiningYear ExperienceInCurrentDomain PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model DT --error_type MNAR --error_pcts 0.2 --error_cols JoiningYear --pattern_cols JoiningYear PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model DT --error_type MNAR --error_pcts 0.3 --error_cols JoiningYear --pattern_cols JoiningYear City_New_Delhi Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model DT --error_type MNAR --error_pcts 0.4 --error_cols Age --pattern_cols Age JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model DT --error_type MNAR --error_pcts 0.5 --error_cols JoiningYear --pattern_cols JoiningYear Education Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model RF --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model RF --error_type MNAR --error_pcts 0.1 --error_cols JoiningYear --pattern_cols JoiningYear PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model RF --error_type MNAR --error_pcts 0.2 --error_cols JoiningYear --pattern_cols JoiningYear Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model RF --error_type MNAR --error_pcts 0.3 --error_cols JoiningYear --pattern_cols JoiningYear Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model RF --error_type MNAR --error_pcts 0.4 --error_cols JoiningYear --pattern_cols JoiningYear Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model RF --error_type MNAR --error_pcts 0.5 --error_cols JoiningYear --pattern_cols JoiningYear Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model NN --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model NN --error_type MNAR --error_pcts 0.1 --error_cols Education --pattern_cols Education Age PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model NN --error_type MNAR --error_pcts 0.2 --error_cols Education --pattern_cols Education PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model NN --error_type MNAR --error_pcts 0.3 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model NN --error_type MNAR --error_pcts 0.4 --error_cols Age --pattern_cols Age City_Pune Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning IterativeImputer --model NN --error_type MNAR --error_pcts 0.5 --error_cols Age --pattern_cols Age City_Pune JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5