python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model LR --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model LR --error_type MNAR --error_pcts 0.1 --error_cols Education --pattern_cols Education ExperienceInCurrentDomain PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model LR --error_type MNAR --error_pcts 0.2 --error_cols Gender --pattern_cols Gender EverBenched Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model LR --error_type MNAR --error_pcts 0.3 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model LR --error_type MNAR --error_pcts 0.4 --error_cols Gender --pattern_cols Age Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model LR --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender EverBenched Education Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model DT --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model DT --error_type MNAR --error_pcts 0.1 --error_cols JoiningYear --pattern_cols JoiningYear PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model DT --error_type MNAR --error_pcts 0.2 --error_cols ExperienceInCurrentDomain --pattern_cols ExperienceInCurrentDomain Age City_New_Delhi Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model DT --error_type MNAR --error_pcts 0.3 --error_cols Gender --pattern_cols Gender Education Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model DT --error_type MNAR --error_pcts 0.4 --error_cols JoiningYear --pattern_cols JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model DT --error_type MNAR --error_pcts 0.5 --error_cols Age --pattern_cols Age JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model RF --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model RF --error_type MNAR --error_pcts 0.1 --error_cols JoiningYear --pattern_cols JoiningYear EverBenched PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model RF --error_type MNAR --error_pcts 0.2 --error_cols JoiningYear --pattern_cols JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model RF --error_type MNAR --error_pcts 0.3 --error_cols JoiningYear --pattern_cols JoiningYear PaymentTier Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model RF --error_type MNAR --error_pcts 0.4 --error_cols JoiningYear --pattern_cols JoiningYear Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model RF --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender Education Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5

python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model NN --error_type MNAR --error_pcts 0 --error_cols Gender --pattern_cols Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model NN --error_type MNAR --error_pcts 0.1 --error_cols Education --pattern_cols Education Age Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model NN --error_type MNAR --error_pcts 0.2 --error_cols Gender --pattern_cols Gender EverBenched Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model NN --error_type MNAR --error_pcts 0.3 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model NN --error_type MNAR --error_pcts 0.4 --error_cols Gender --pattern_cols Gender Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5
python dataclean_allvalue.py --dataset employee --cleaning MedianImputer --model NN --error_type MNAR --error_pcts 0.5 --error_cols Gender --pattern_cols Gender Age EverBenched Y --sens_attr Gender --objective AUC --n_trials 100 --n_processes 5